# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: install dotnet tools
        run: dotnet tool install --global dotnet-ef --version 8.0.4

      - name: build migration bundle - Identity
        run: dotnet ef migrations bundle --context IdentityContext --self-contained -r linux-x64 --verbose

      - name: build migration bundle - Data
        run: dotnet ef migrations bundle --context DataContext --self-contained -r linux-x64 --verbose

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Install EF Tool
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Log into Azure CLI with service principal
        uses: azure/login@v1.4.2
        with:
          creds: ${{ secrets.AZURECREDENTIALS }}
        
      - name: Deploy EF Migrations - Identity      
        working-directory:  ./src/Server
        run: |
            echo "${{ secrets.EF_MIGRATIONS_CONNECTION }}"
            dotnet ef database update --context IdentityContext --configuration Release --connection " ${{ secrets.EF_MIGRATIONS_CONNECTION }}"

      - name: Deploy EF Migrations - Videos      
        working-directory:  ./src/Server
        run: |
            echo "${{ secrets.EF_MIGRATIONS_CONNECTION }}"
            dotnet ef database update --context VideosContext --configuration Release --connection " ${{ secrets.EF_MIGRATIONS_CONNECTION }}"

      - name: Deploy EF Migrations - Comments      
        working-directory:  ./src/Server
        run: |
            echo "${{ secrets.EF_MIGRATIONS_CONNECTION }}"
            dotnet ef database update --context CommentsContext --configuration Release --connection " ${{ secrets.EF_MIGRATIONS_CONNECTION }}"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-alices-website'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .